* Elastic Stack
Relialbly and Securely take data from any source, in any format, then search, analyze and visualize it in real time.
Elastic Stack is consist of
- Kibana
- Elasticsearch
- Beats
- Logstash
** Who Uses elastic stack?
- Netflix
- Stack Overflow
- Linked In
- Medium
- Github
- Twilio
- and many more.
*** Sources
- https://www.elastic.co/customers/
- https://logz.io/blog/15-tech-companies-chose-elk-stack/

** Use Cases
*** Logging
  - Activision Blizzard:
  To store and analyze gamer and server event
*** Metrics
  - Mars Curiousity Rover by Nasa
  Sends telemetry sensor and photo data into the elastic stack
  for analysis so if someone want to know how hot mars is on an hourly daily basis
  you can go and follow the data
*** Security Analytics
- Slack
  Use Elastic Stack to secure communication to their channel
*** Business Analytics
- Tinder
  Tinder use elastic stack to match people

** Elasticsearch
Elasticsearch is known as the heart of elastic stack and this is where you can store, search, and analyze your data.

Great Search Experience = Get fast and relevant results, no matter the scale.

*** Relevance of a search
Precision and recall is used to measure the relevance of a search.
**** True Positives
Relevant documents that are returned to the user

**** False Positives
Irelvant documents that are returned to the user

**** True Negatives
Irelvant documents that are not returned to the user

**** False Negatives
Relevant documents that are not returned to the user


*** Precision and recall
Precision and recall are inversely related.
Precision want all the results to be a perfect match to the query, even if it means returning less documents.
Recall want to retrieve more results event if documents may not be a perfect match to the query.
Precision and recall determine which documents are included in the search results.
Precision and recall do not determine which of the returned documents are more relevant compared to the other!

**** Precision
What portion of the retrieved data is actually relevant to the search query?
precision = TP / (TP + FP)

**** Recall
What portion of relevant data is being returned as search results?
recall = TP / (TP + FN)

*** Ranking
Ranking refers to ordering of the results(from most relevant at the top, to least relevant at the bottom).
*** Score
- the score is a value represent how relevant a document is to that specific query
- A score is computed for each document taht is a hit
- hits are search result that are sent to the user.
**** How to compute a score?
- Term Frequency(TF)
- Inverse Document Frequency(IDF)
- And more

**** Term Frequency(TF)
determines how many times each search term appears in a document.
If search terms are found in high frequency in a document is considered more relevant to the search query.

**** Inverse Document Frequency
IDF diminishes the weight of terms that occur in the document set and increases the weight of terms that occur rarely!
** Kibana
Visualize and manage data.

* Writing reference link
https://www.youtube.com/watch?v=gS_nHTWZEJ8
